#!/usr/bin/env perl
use strict;
use warnings;
use Term::ANSIColor;
use File::Spec::Functions qw(catfile);
use File::Path            qw(remove_tree);
use POSIX ":sys_wait_h";
use Getopt::Long;
use Cwd qw(getcwd);

my $VERBOSE = 0;
GetOptions( "verbose" => \$VERBOSE );

my $start_time = time();
my $cwd        = getcwd();

sub timestamp {
    my @t = localtime();
    return sprintf( "[%02d:%02d:%02d]", $t[2], $t[1], $t[0] );
}

sub log_line {
    my ( $color, $tag, $msg ) = @_;
    print color($color), sprintf( "%s %-10s", timestamp(), "[$tag]" ),
      color('white'), " $msg\n", color('reset');
}

sub info  { log_line( 'green',  'INFO',  "@_" ); }
sub warn  { log_line( 'yellow', 'WARN',  "@_" ); }
sub error { log_line( 'red',    'ERROR', "@_" ); }
sub diex  { error(@_); exit 1 }

sub section {
    my ($title) = @_;
    print color('cyan'), "\n=== $title ===\n", color('reset');
}

sub run {
    my ( $cmd, $dir ) = @_;
    $dir ||= '.';

    info "($dir) $cmd" if $VERBOSE;
    my $pid = fork();

    if ( $pid == 0 ) {
        chdir $dir or diex "Failed to cd into $dir: $!";
        exec "sh", "-c", $cmd or diex "Exec failed: $!";
    }

    waitpid( $pid, 0 );
    my $exit = $? >> 8;

    if ( $exit != 0 ) {
        error "Command failed: $cmd (exit code $exit)";
        exit $exit;
    }

    return $exit;
}

sub boot {
    section "Bootstrapping Project";
    my @dirs = ( '.', 'src' );
    my $os   = $^O;
    my $cmd  = 'autoreconf -i';

    if ( $os eq 'MSWin32' ) {
        info "Detected Windows environment";
        my $ac = $ENV{ACLOCAL_PATH} // '';
        $ac =~ s/;/:/g;
        $ac =~ s|\\|/|g;
        $ac =~ s|([A-Za-z]):/|/$1/|g;
        $cmd = "ACLOCAL_PATH=$ac autoreconf -i";
    }

    if ( $os eq 'darwin' ) {
        info "Detected macOS, performing additional setup...";
        run("aclocal");
        for my $d (@dirs) {
            if ( -f catfile( $d, "configure.ac" ) ) {
                run( "automake --add-missing", $d );
            }
        }
    }

    my $fail = 0;
    for my $d (@dirs) {
        next unless -f catfile( $d, "configure.ac" );
        info "Running autoreconf in $d...";
        my $code = run( $cmd, $d );
        $fail ||= $code != 0;
    }

    $fail
      ? diex "Autoreconf failed"
      : info "Autoreconf completed successfully.";
}

sub clean {
    section "Cleaning Project";
    my @targets = qw(
      autom4te.cache config.log config.status Makefile Makefile.in
      src/.deps src/Makefile src/Makefile.in
      tests/.deps tests/Makefile tests/Makefile.in
      configure aclocal.m4
      config/compile config/depcomp config/install-sh config/missing config/test-driver
    );

    if ( -e "Makefile" ) {
        info "Running make clean...";
        system( "make", "clean" );
    }

    for my $t (@targets) {
        next unless -e $t;
        if   ( -d $t ) { remove_tree($t); }
        else           { unlink $t; }
        info "Removed $t" if $VERBOSE;
    }

    info "Cleanup complete.";
}

sub build {
    section "Building Project";
    run("./configure");
    run("make");
    info "Build complete.";
}

sub check {
    section "Running Tests";
    run("make check");
    info "All tests passed.";
}

sub rebuild {
    section "Full Rebuild";
    clean();
    build();
}

my %commands = (
    boot    => \&boot,
    clean   => \&clean,
    build   => \&build,
    check   => \&check,
    rebuild => \&rebuild,
);

my $cmd = shift // 'boot';
if ( exists $commands{$cmd} ) {
    $commands{$cmd}->();
}
else {
    diex
"Unknown command: '$cmd'\nUsage: $0 [boot|clean|build|check|rebuild] [--verbose]";
}

my $elapsed = time() - $start_time;
info sprintf( "Completed in %ds", $elapsed );
